# Site
name: 'Towards Polymath '
description: 'Blog for odds and ends'
logo: 'assets/images/logo.png'
favicon: 'assets/images/ai_engieer.png'
baseurl: ''
disqus: 'mbyun1420-github-io'
email: 'mbyun1420@gmail.com'
# mailchimp - 쓰지 않는 것으로 
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Sal
      site:           https://www.wowthemes.net
      avatar:         assets/images/avatar1.jpg
      bio:            "Hi, I am Sal, the author of Mundana, the theme you're currently previewing. I hope you like it!"
      email:          wowthemesnet@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    jane:
      name:           Jane
      site:           https://www.wowthemes.net
      avatar:         assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          fakemail@gmail.com
      twitter:        https://twitter.com/wowthemesnet
 
    youn:
      name:           Youn
      site:           https://mbyun1420.github.io/
      avatar:         assets/images/profile_author_youn.jpg
      bio:            "Be happy"
      email:          mbyun1420@gmail.com

    signal-processing-engineer:
      name:           Signal-processing-engineer
      site:           https://mbyun1420.github.io/
      avatar:         assets/images/profile_author_youn.jpg
      bio:            "Signal processing engineer Youn "
      email:          mbyun1420@gmail.com

    software-engineer:
      name:           Software-engineer
      site:           https://mbyun1420.github.io/
      avatar:         assets/images/profile_author_youn.jpg
      bio:            "Software engineer Youn "
      email:          mbyun1420@gmail.com

    mechanical-engineer:
      name:           Mechanical-engineer
      site:           https://mbyun1420.github.io/
      avatar:         assets/images/profile_author_youn.jpg
      bio:            "Mechanical engineer Youn "
      email:          mbyun1420@gmail.com

    electrical-engineer:
      name:           Electrical-engineer
      site:           https://mbyun1420.github.io/
      avatar:         assets/images/profile_author_youn.jpg
      bio:            "Electrical engineer Youn "
      email:          mbyun1420@gmail.com

    data-scientist:
      name:           Data-scientist
      site:           https://mbyun1420.github.io/
      avatar:         assets/images/profile_author_youn.jpg
      bio:            "Data scientist Youn "
      email:          mbyun1420@gmail.com



# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: youn
      avatar: /assets/images/ai_engieer.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate (10->5)
paginate: 5 



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]